<?php

namespace AppBundle\Repository;

/**
 * EfunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EfunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
