<?php

namespace AppBundle\Repository;

/**
 * EtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtypeRepository extends \Doctrine\ORM\EntityRepository
{
}
