<?php

namespace AppBundle\Repository;

/**
 * VerificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerificationRepository extends \Doctrine\ORM\EntityRepository
{
}
